## Лабораторная работа №1 | Вариант 7

Выполнил:

### 1. Numpy

In [1]:
import numpy as np

1. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [2]:
0 * np.nan

nan

In [3]:
np.nan == np.nan

False

In [4]:
np.inf > np.nan

False

In [5]:
np.nan - np.nan

nan

In [6]:
np.nan in set([np.nan])

True

In [7]:
0.3 == 3 * 0.1

False

2. Создайте матрицу 5х5 со значениями 1, 2, 3, 4 ниже диагонали

In [8]:
mas = np.identity(5, dtype=int)
array1 = np.array([1, 2, 3, 4])
for i in range(5):
  for j in range (5):
    if i > j:
      mas[i][j] = array1[j - i]
print(mas)

[[1 0 0 0 0]
 [4 1 0 0 0]
 [3 4 1 0 0]
 [2 3 4 1 0]
 [1 2 3 4 1]]


3. Создайте матрицу 8х8 и заполните ее паттерном шахматной доски

In [9]:
mas = np.zeros([8, 8], dtype = int)
mas[::2, ::2] = 1
mas[1::2, 1::2] = 1
mas

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

4. Умножте матрицу 5х3 и 3х2 (матричное умножение)

In [10]:
mas1 = np.random.randint(0, 10, size = (5,3))
mas1

array([[8, 2, 3],
       [3, 4, 4],
       [1, 4, 9],
       [4, 6, 2],
       [4, 7, 8]])

In [11]:
mas2 = np.random.randint(0, 10, size = (3,2))
mas2

array([[6, 4],
       [6, 5],
       [8, 6]])

In [12]:
res = mas1.dot(mas2)
res

array([[ 84,  60],
       [ 74,  56],
       [102,  78],
       [ 76,  58],
       [130,  99]])

5. Как получить все даты, соответствующие июлю 2016 года?

In [13]:
year = 2016
month = 7  # Апрель

# Создаем массив дат для указанного года и месяца
dates = np.arange(np.datetime64(f'{year}-{str(month).zfill(2)}-01'),
                  np.datetime64(f'{year}-{str(month+1).zfill(2)}-01'))
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

6. Создайте матрицу размером 5х5 со случайными значениями строк в диапазоне от 0 до 4

In [14]:
mas = np.random.randint(0, 5, size = [5,5])
mas

array([[2, 2, 0, 0, 1],
       [3, 0, 3, 2, 0],
       [2, 3, 3, 4, 2],
       [3, 4, 1, 4, 3],
       [3, 0, 1, 4, 0]])

7. Создайте вектор размером 10 со значениями в диапазоне от $(0, 1)$

In [15]:
mas = np.random.random_sample(size = 10)
mas
#можно использовать uniform разница в том, что uniform генерирует числа включая верхнюю границу

array([0.07339662, 0.6956766 , 0.55191386, 0.60325605, 0.84772698,
       0.71918153, 0.83914786, 0.5616507 , 0.46466128, 0.71075964])

8. Выведите минимальное и максимальное представимое значение для каждого скалярного типа numpy

In [16]:
ints = [np.int8, np.int32, np.int64]

for dtype in ints:
   print(f'Тип: {dtype.__name__}, минимум: {np.iinfo(dtype).min}, максимум: {np.iinfo(dtype).max}')

floats = [np.float32, np.float64]
for dtype in floats:
   print(f'Тип: {dtype.__name__}, минимум: {np.finfo(dtype).min}, максимум: {np.finfo(dtype).max}')

Тип: int8, минимум: -128, максимум: 127
Тип: int32, минимум: -2147483648, максимум: 2147483647
Тип: int64, минимум: -9223372036854775808, максимум: 9223372036854775807
Тип: float32, минимум: -3.4028234663852886e+38, максимум: 3.4028234663852886e+38
Тип: float64, минимум: -1.7976931348623157e+308, максимум: 1.7976931348623157e+308


9. Как отсортировать массив по n-му столбцу?

In [17]:
mas = np.random.randint(1, 10, size=(5, 5))
mas


array([[5, 7, 7, 5, 4],
       [2, 3, 5, 1, 2],
       [6, 4, 8, 2, 3],
       [4, 6, 9, 9, 6],
       [7, 6, 8, 8, 8]])

In [18]:
n = 1
sorted_mas = mas[mas[:, n].argsort()]
sorted_mas


array([[2, 3, 5, 1, 2],
       [6, 4, 8, 2, 3],
       [4, 6, 9, 9, 6],
       [7, 6, 8, 8, 8],
       [5, 7, 7, 5, 4]])

10. Как определить, есть ли в данном двумерном массиве пустые столбцы?

In [19]:
mas = np.array([[1, 0, 0],
                [3, 0, 4],
                [0, 0, 6]])
flag = 0;
for j in range(mas.shape[1]):
  if np.all(mas[:, j] == 0):
    print("YES")
  else:
    print("NO")

NO
YES
NO


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом

Набор данных для изучения зависимости различных параметров тела человека.

Файл: `data.csv`

```
Height (cm) - рост человека в сантиметрах
Weight (kg) - вес человека в килограммах
Blood Pressure (s/d) - кровяное давление(systolic/diastolic) в mmHg.
Cholesterol Level (mg/dL) - уровень холестерина milligrams per deciliter.
BMI - Body Mass Index, рассчитывается по весу и росту.
Blood Glucose Level (mg/dL) - уровень глюкозы в крови milligrams per deciliter.
Bone Density (g/cm²) - плотность костной массы grams per square centimeter.
Vision Sharpness - четкость зрения от 0 (полностью размыто) до 100 (идеально).
Hearing Ability (dB) - способность воспринимать звуки в dB.
Physical Activity Level - уровень физической активности 'Low', 'Moderate', или 'High'.
Smoking Status - статус курильщика 'Never', 'Former', и 'Current'.
Alcohol Consumption - частота принятия алкоголя.
Diet - тип диеты. Категоризован на 'Balanced', 'High Protein', 'Low Carb', и т.п.
Chronic Diseases - наличие хронических заболеваний (e.g., diabetes, hypertension).
Medication Use - использование медикаментов.
Family History - наличие в семейном анамнезе возрастных заболеваний.
Cognitive Function - самооценка когнитивных функций по шкале от 0 (плохая) до 100 (отличная).
Mental Health Status - самооценка состояния психического здоровья по шкале от 0 (плохое) до 100 (отличное).
Sleep Patterns - среднее кол-во сна за ночь.
Stress Levels - самооценка уровня стресса по шкале от 0 (низкий) до 100 (высокий).
Pollution Exposure - воздействие загрязнения, измеряемое в произвольных единицах измерения.
Sun Exposure - среднее время пребывания на солнце в часах в неделю.
Education Level - уровень образования.
Income Level - доход в USD.
```

In [2]:
import pandas as pd

In [7]:
df = pd.read_csv('data.csv', delimiter = ',')
df

Gender  Height (cm)  Weight (kg) Blood Pressure (s/d)  \
0       Male   171.148359    86.185197              151/109   
1       Male   172.946206    79.641937              134/112   
2     Female   155.945488    49.167058              160/101   
3     Female   169.078298    56.017921               133/94   
4     Female   163.758355    73.966304              170/106   
...      ...          ...          ...                  ...   
2995    Male   161.632502    88.323405               134/91   
2996    Male   163.443512    93.217007               110/78   
2997    Male   177.857644    86.258847              159/116   
2998  Female   162.287164    41.371018               134/82   
2999    Male   175.341710    78.718038               167/91   

      Cholesterol Level (mg/dL)        BMI  Blood Glucose Level (mg/dL)  \
0                    259.465814  29.423017                   157.652848   
1                    263.630292  26.626847                   118.507805   
2                    207.846206  20.217553                   143.587550   
3                    253.283779  19.595270                   137.448581   
4                    236.119899  27.582078                   145.328695   
...                         ...        ...                          ...   
2995                 204.175510  33.807917                   112.075747   
2996                 197.384424  34.894725                   101.177692   
2997                 238.641542  27.268332                   110.548146   
2998                 198.244328  15.708252                   123.704379   
2999                 279.118184  25.603762                   156.577316   

      Bone Density (g/cm²)  Vision Sharpness  Hearing Ability (dB)  ...  \
0                 0.132868          0.200000             58.786198  ...   
1                 0.629534          0.267312             54.635270  ...   
2                 0.473487          0.248667             54.564632  ...   
3                 1.184315          0.513818             79.722963  ...   
4                 0.434562          0.306864             52.479469  ...   
...                    ...               ...                   ...  ...   
2995              1.583006          0.665907             27.997736  ...   
2996              1.785129          0.720304             32.866623  ...   
2997              0.366012          0.200000             39.756270  ...   
2998              1.452963          0.648158             43.338594  ...   
2999              0.704319          0.578625             43.926230  ...   

     Family History Cognitive Function Mental Health Status Sleep Patterns  \
0               NaN          44.059172                 Good       Insomnia   
1     Heart Disease          45.312298                 Good         Normal   
2      Hypertension          56.246991                 Poor       Insomnia   
3      Hypertension          55.196092                 Poor       Insomnia   
4               NaN          53.023379                 Good         Normal   
...             ...                ...                  ...            ...   
2995       Diabetes          57.820282                 Fair         Normal   
2996  Heart Disease          68.783715                 Good         Normal   
2997            NaN          50.133807                 Fair         Normal   
2998   Hypertension          68.864629                 Good       Insomnia   
2999   Hypertension          60.892114                 Poor       Insomnia   

     Stress Levels Pollution Exposure Sun Exposure  Education Level  \
0         2.797064           5.142344     7.108975              NaN   
1         9.339930           7.272720     3.918489    Undergraduate   
2         9.234637           8.500386     5.393408              NaN   
3         4.693446           7.555511     2.745578              NaN   
4         4.038537           9.429097     3.878435    Undergraduate   
...            ...                ...          ...              ...   
2995      8.0

1. Какой средний вес людей представленных в наборе данных?

In [11]:
mean_weight = df['Weight (kg)'].mean()
mean_weight

72.53726013905388

2. Сбалансировано ли соотношение мужчин и женщин в наборе данных?

In [14]:
count_fem = len(df[df['Gender']=='Female'])
count_male = len(df[df['Gender']=='Male'])

In [16]:
balanced = count_fem / count_male
balanced
#близко к единице следовательно сбалансировано

1.0147750167897918

3. Правда ли, что люди с высоким уровнем стресса имеют более высокое кровяное давление, чем те, кто не подвержен стрессу

In [24]:
df.dtypes

Gender                          object
Height (cm)                    float64
Weight (kg)                    float64
Blood Pressure (s/d)            object
Cholesterol Level (mg/dL)      float64
BMI                            float64
Blood Glucose Level (mg/dL)    float64
Bone Density (g/cm²)           float64
Vision Sharpness               float64
Hearing Ability (dB)           float64
Physical Activity Level         object
Smoking Status                  object
Alcohol Consumption             object
Diet                            object
Chronic Diseases                object
Medication Use                  object
Family History                  object
Cognitive Function             float64
Mental Health Status            object
Sleep Patterns                  object
Stress Levels                  float64
Pollution Exposure             float64
Sun Exposure                   float64
Education Level                 object
Income Level                    object
Age (years)              

In [39]:
df_sort = df.sort_values(by = 'Stress Levels', ascending = False)
df_sort

Gender  Height (cm)  Weight (kg) Blood Pressure (s/d)  \
1053  Female   157.488860    65.061187               139/84   
966   Female   163.730370    64.878755              187/103   
1496  Female   156.727756    64.660854              150/105   
201   Female   165.311316    71.802302               168/93   
1832    Male   162.468639    99.366215              153/107   
...      ...          ...          ...                  ...   
1742  Female   153.101065    65.387315               148/73   
2555  Female   156.356745    82.587187               124/86   
1804    Male   171.698665    76.865576               164/99   
326     Male   177.228611    83.459019               153/98   
2189  Female   154.236278    66.051947               127/94   

      Cholesterol Level (mg/dL)        BMI  Blood Glucose Level (mg/dL)  \
1053                 196.218026  26.231450                   115.299340   
966                  237.739981  24.201597                   135.509748   
1496                 247.411474  26.323862                   134.341884   
201                  236.509295  26.274424                   155.962488   
1832                 274.177742  37.644338                   150.686463   
...                         ...        ...                          ...   
1742                 268.117250  27.895688                   112.637637   
2555                 232.634169  33.781539                   146.904556   
1804                 211.404672  26.073423                    98.526171   
326                  267.611775  26.570860                   133.816463   
2189                 176.426871  27.765951                   113.263628   

      Bone Density (g/cm²)  Vision Sharpness  Hearing Ability (dB)  ...  \
1053              1.497706          0.736307             25.113472  ...   
966               0.360586          0.200000             65.645534  ...   
1496              0.508217          0.309987             57.767344  ...   
201               1.520918          0.708114             46.792139  ...   
1832             -0.012821          0.200000             66.562346  ...   
...                    ...               ...                   ...  ...   
1742              1.086315          0.713353             59.114878  ...   
2555              1.672695          0.876516             29.045584  ...   
1804              0.982144          0.231406             46.637613  ...   
326               0.091927          0.200000             71.489531  ...   
2189              1.269975          0.523051             27.029954  ...   

     Family History Cognitive Function Mental Health Status Sleep Patterns  \
1053       Diabetes          73.204391                 Fair         Normal   
966   Heart Disease          54.814537            Excellent       Insomnia   
1496            NaN          53.606102                 Poor       Insomnia   
201    Hypertension          78.127851            Excellent         Normal   
1832            NaN          67.154446            Excellent       Insomnia   
...             ...                ...                  ...            ...   
1742            NaN          60.604529                 Fair         Normal   
2555   Hypertension          55.494238                 Fair         Normal   
1804       Diabetes          72.180779            Excellent       Insomnia   
326             NaN          47.009621                 Fair       Insomnia   
2189  Heart Disease          70.415398                 Good       Insomnia   

     Stress Levels Pollution Exposure Sun Exposure  Education Level  \
1053      9.996323           4.053786     6.554834      High School   
966       9.994695           1.384646     5.087317    Undergraduate   
1496      9.991990           3.856749     4.174231     Postgraduate   
201       9.984869           5.413626     3.408701     Postgraduate   
1832      9.983047           3.504055     8.936955              NaN   
...            ...                ...          ...              ...   
1742      1.0

In [55]:
df[['Blood Pressure s', 'Blood Pressure d']] = df['Blood Pressure (s/d)'].str.split('/', expand = True, n = 1)
df['Blood Pressure s'] = df['Blood Pressure s'].astype(int)
mean_high_stress = df.loc[df['Stress Levels'] > 7, 'Blood Pressure s'].mean()
mean_low_stress = df.loc[df['Stress Levels'] < 3, 'Blood Pressure s'].mean()

In [56]:
mean_high_stress

145.8617234468938

In [58]:
mean_low_stress
#Давление одинаковое => следовательно никакой зависимости нет

145.455223880597

4. Правда ли, что уровень холестерина у мужчин и женщин отличается?

In [60]:
chol_level_male = df.loc[df['Gender'] == 'Female', 'Cholesterol Level (mg/dL)'].mean()
chol_level_male

234.15302825574207

In [62]:
chol_level_male = df.loc[df['Gender'] == 'Male', 'Cholesterol Level (mg/dL)'].mean()
chol_level_male
#Одинаковый уровень

233.9047396169502

5. Правда ли, что с возрастом женщины имеют свойство оценивать свои когнитивные способности хуже, чем в юности (порог юности - 30 лет, женщина в возрасте - 60 лет+)

In [69]:
cog_level_old = df.loc[(df['Gender'] == 'Female') & (df['Age (years)'] > 60), 'Cognitive Function'].mean()
cog_level_old

57.665728241849315

In [70]:
cog_level_young = df.loc[(df['Gender'] == 'Female') & (df['Age (years)'] < 30), 'Cognitive Function'].mean()
cog_level_young

72.84317149446179

In [76]:
dif_cog_level =  1 - cog_level_old / cog_level_young
dif_cog_level
#Правда, женщины в возрасте оценивают себя на 20 процентов хуже

0.20835780404984705

6. Влияет ли физическая активность на вес в возрасте более 50 лет?

In [98]:
phys_act_low = df.loc[(df['Physical Activity Level'] == 'Low') & (df['Age (years)'] > 50), 'Weight (kg)'].mean()
phys_act_mod = df.loc[(df['Physical Activity Level'] == 'Moderate') & (df['Age (years)'] > 50), 'Weight (kg)'].mean()
phys_act_high = df.loc[(df['Physical Activity Level'] == 'High') & (df['Age (years)'] > 50), 'Weight (kg)'].mean()

In [104]:
phys_act_low

74.36552503757412

In [103]:
phys_act_mod

72.07604748397078

In [102]:
phys_act_high
#Можно отметить что разница в весе между женщинами 50+ с разными уровнями физ.активности в среднем составляет 2 килограмма

70.42802647863721

7. Сравните минимальный вес мужчин с высоким и низким заработком

In [112]:
min_income_weight = df.loc[df['Income Level'] == 'Low', 'Weight (kg)'].min()
min_income_weight

36.19276502392557

In [113]:
high_income_weight = df.loc[df['Income Level'] == 'High', 'Weight (kg)'].min()
high_income_weight

32.53767213511866

In [117]:
min_income_weight - high_income_weight
#Разница 3кг - возможно влияет уровень стресса, а возможно просто погрешность(интересно проверить)

3.655092888806905

8. Правда ли, что у людей с индексом массы тела больше 75го перцентиля встречаются хронические заболевания чаще, чем у людей с индесом массы тела в переделах от 30 до 60 перцентиля?

In [118]:
df['Chronic Diseases']

0                NaN
1       Hypertension
2       Hypertension
3           Diabetes
4                NaN
            ...     
2995    Hypertension
2996        Diabetes
2997             NaN
2998        Diabetes
2999    Hypertension
Name: Chronic Diseases, Length: 3000, dtype: object

9. Правда ли, что люди с высоким уровнем дохода имеют больший уровень физической активности, чем люди с низким доходом

10. Какая доля мужчин с высокой частотой пребывания на солнце имеет высокий заработок?

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Визуализируйте частоту встречаемых хронических заболеваний

2. Как связана оценка собственных когнитивных функций с уровнем стресса?

3. Визуализируйте как зависит вес от роста человека

4. Постройте box plot отображающий распределение уровня стресса у людей с различным уровнем дохода

5. Постройте круговую диаграмму отображающую как ментальное здоровье связано с паттернами сна

6. Имеет ли связь зрение и способность слышать звуки на высоких частотах? Ответьте на вопрос - какая зависимость между ними и предположите почему зависимость именно такая?

7. Красиво визуализируйте как связаны между собой уровень дохода, когнитивные способности и уровень стресса*

\* Задание на доп. балл